config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

 root 'static_pages#landing_page'
  
  get "about" => "static_pages#about" 
  get "contact" => "static_pages#contact" 

  post 'static_pages/thank_you'

  post '/payments/create'

devise_for :users, :controllers => {users: 'sessions', registrations: 'registrations'} 

 devise_scope :user do
    get 'login', to: "devise/sessions#new", as: "login"
    get 'logout', to: "devise/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy'     
    get 'signup', to: "users#new", as: "signup"
  end

  
  resources :payments

  resources :products do
    resources :comments
  end
  resources :users
  
  resources :surveys

  resources :orders, only: [:index, :show, :new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	belongs_to :user
	validates :name, presence:true 

	validates :price, :numericality => { :greater_than => 0 }

	def average_rating
		comments.average(:rating).to_f
	end 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
    @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order("created_at DESC")
    @comments = Comment.where(:product_id => @product.id).paginate(:per_page => 5, :page => params[:page])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy 
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container" id="product">
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel-body">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/products/edit.html.erb
<div class="panel-heading container"><h1>Editing Product</h1></div>

<%= render 'form' %>
<div class="container">
<div class="panel-footer">
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/index.html.erb
<div class="container">
    
  <p id="notice"><%= notice %></p>  



    <div class="panel-heading"><h1>Listing Products </h1></div>
<div class="panel-body">
    

<div>
  <%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
  </div>
<hr>
  <div class="container">
  <div class="row">
  <div class="col-lg-12">
  <table class="table products-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Image</th>
      <th>Color</th>
      <th>Price</th>
      <th>Pay</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.category %></td>
        <td class="img_url"><%= product.image_url %></td>
        <td><%= image_tag(product.image_url) %></td>
        <td class="img-url"><%= product.image_url %></td>
        <td class="product-image"><%= image_tag(product.image_url) %></td>
        <td><%= product.color %></td>
        <td>$<%= product.price %></td>
        <td><%= form_tag "/payments/create"  do %>
       
  <%= render partial: "shared/stripe_checkout_button" %>
<% end %></td>
        <td><%= link_to 'Show', product, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-success" %></td>
        <% if signed_in? && current_user.admin %>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

<br>
</div>

</div>

app/views/products/new.html.erb
<div class="container">

<div class="panel-heading"><h1>New Product</h1></div>
</div>
</div>
<%= render 'form' %>
<div class="container">
<div class="panel-footer">
	<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/product.html.erb
<!<% @products.each do |product| %>
<!<%= render product %>
<!<% end %>

<%= render partial: "product", collection: @products %>

app/views/products/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="panel-heading"><h1>Product Details </h1></div>

<div class="panel-body">
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
	<strong>Color:</strong>
	<%= @product.color %>
</p>
<p>
	<strong>Price:</strong>
	<%= @product.price %>
</p>
<%= form_tag "/payments/create" do %>
  <%= render partial: "shared/stripe_checkout_button" %>
<% end %>
</div>

<div class="avg-rating"><p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></p></div>

<div class="form-group">
<h2>Comments:</h2>
<%= render @product.comments.build %>

<div class="pagination"><%= will_paginate @comments %></div>


<h2>Add a Review:</h2>
<%= render 'comments/form' %>
</div>

<div class="footer">
<div class="container">
<div class="col-md-12">
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>
</div>
</div>