config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

 root 'static_pages#landing_page'
  
  get "about" => "static_pages#about" 
  get "contact" => "static_pages#contact" 

  post 'static_pages/thank_you'

  post '/payments/create'

devise_for :users, :controllers => {users: 'sessions', registrations: 'registrations'} 

 devise_scope :user do
    get 'login', to: "devise/sessions#new", as: "login"
    get 'logout', to: "devise/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy'     
    get 'signup', to: "users#new", as: "signup"
  end

  
  resources :payments

  resources :products do
    resources :comments
  end
  resources :users
  
  resources :surveys

  resources :orders, only: [:index, :show, :new, :create]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin? 
  	can :manage, :all
	else
 	can :read, :all
	end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :body, presence: true 
  validates :user, presence: true 
  validates :product, presence: true 
  validates :rating, numericality: { only_integer: true}


end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	belongs_to :user
	validates :name, presence:true 

	validates :price, :numericality => { :greater_than => 0 }

	def average_rating
		comments.average(:rating).to_f
	end 

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  else
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  end

  has_many :orders
  has_many :products
  has_many :users

  def to_s
  	first_name
  end



private

  def welcome_email 
    UserMailer.welcome_message(self).deliver
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = User.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :js

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      else
        flash_type.to_s
    end
  end

  def bootstrap_alt_class_for(flash_type)
    case flash_type
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
      <!-- FOOTER -->
      <div class="container">
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
<div class="container">
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Coffee and More</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav subpage_nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <% if user_signed_in? %>     
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>             
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <div class="container">
        <%= form_tag("/products", method: "get", class: "navbar-form") do %>
          <%= label_tag(:q, "Search for:", class:"label label-primary") %>
          <%= text_field_tag(:q, "coffee", class:"form-control")%>
          <%= submit_tag("Search", class:"btn btn-primary") %>
        <% end %>
        </div>
        </div>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

</div>
</div> <!-- navbar-wrapper -->

app/views/layouts/_info.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_alt_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_lander.html.erb
<div class="carousel slide" data-interval="5000" data-ride="carousel" id=
    "carousel-example-generic">
        <!-- Indicators -->
        
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target="#carousel-example-generic"></li>

            <li data-slide-to="1" data-target="#carousel-example-generic"></li>

            <li data-slide-to="2" data-target="#carousel-example-generic"></li>
        </ol><!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">
            <div class="item active">
            <img class="first-slide" src="https://download.unsplash.com/44/fN6hZMWqRHuFET5YoApH_StBalmainCoffee.jpg">
                <div class="container">
                <div class="carousel-caption">
                        <p><%= render partial: "layouts/info", flash: flash %> </p>        

<h1>Welcome to my App!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-primary btn-lg" %>
    <%= link_to "View Products", products_path , class: "btn btn-default btn-lg" %>
    <% else %>      
    </p>
<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
            <div class="item">
            <img class="second-slide" src="https://download.unsplash.com/photo-1422207134147-65fb81f59e38">
                <div class="container">
                <div class="carousel-caption">
<h1>What are you waiting for?</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-primary btn-lg" %>
    <%= link_to "View Products", products_path , class: "btn btn-default btn-lg" %>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
                        <div class="item">
            <img class="third-slide" src="https://download.unsplash.com/photo-1422310299561-e3b8b45d859f">
                <div class="container">
                <div class="carousel-caption">
<h1>Sign Up Today!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-primary btn-lg" %>
    <%= link_to "View Products", products_path , class: "btn btn-default btn-lg" %>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
        </div><!-- Left and right controls -->

        <a class="left carousel-control" data-slide="prev" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span></a> <a class=
        "right carousel-control" data-slide="next" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span></a>
    </div>

app/views/layouts/_lpheader.html.erb
<div class="navbar-wrapper lp-wrapper">
<div class="container">
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Coffee and More</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <% if user_signed_in? %>     
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>             
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <div class="container">
        <%= form_tag("/products", method: "get",class: "navbar-form") do %>
          <%= label_tag(:q, "Search for:", class:"label label-primary") %>
          <%= text_field_tag(:q, "coffee", class:"form-control", id: "tags")%>
          <%= submit_tag("Search", class:"btn btn-primary") %>
        <% end %>
      </div>
      </div>
    
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container -->
</nav>

</div>
</div> <!-- navbar-wrapper -->

app/views/layouts/_main.html.erb
<div class="carousel slide" data-interval="5000" data-ride="carousel" id=
    "carousel-example-generic">
        <!-- Indicators -->
        
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target="#carousel-example-generic"></li>

            <li data-slide-to="1" data-target="#carousel-example-generic"></li>

            <li data-slide-to="2" data-target="#carousel-example-generic"></li>
        </ol><!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">
            <% @products.each do |product| %>
            <div class="item <%=" active" if product == @products.first %>">
               <%= image_tag(product.image_url) %>
                <div class="container">
                <div class="carousel-caption">
                        <p><%= render partial: "layouts/info", flash: flash %>  </p>       

<h1>Welcome to my App!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-primary btn-lg" %>
    <%= link_to "View Products", products_path , class: "btn btn-default btn-lg" %>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
</p>
    <% end %>
              <p>  <%= product.name %> </p>
                </div>
                </div>
            </div>
            <% end %>

        </div><!-- Left and right controls -->

        <a class="left carousel-control" data-slide="prev" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span></a> <a class=
        "right carousel-control" data-slide="next" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span></a>
    </div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee and More</title>
    <meta name="viewport" content="width=device-width = 1.0,initial-scale = 1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_page? (root_path) %>
<%= render 'layouts/lpheader' %>
<% else %>
<%= render 'layouts/header' %>
<% end %>
		
		<% if flash[:notice].nil? %>
		<% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class:"alert alert-#{name}") %>	    
          <% end %>		
         <% end %>

		<%= yield %>		
            
<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/shared/_layout.erb
<div class="carousel slide" data-interval="5000" data-ride="carousel" id=
    "carousel-example-generic">
        <!-- Indicators -->
        
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target="#carousel-example-generic"></li>

            <li data-slide-to="1" data-target="#carousel-example-generic"></li>

            <li data-slide-to="2" data-target="#carousel-example-generic"></li>
        </ol><!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">
            <div class="item active">
            <img class="first-slide" src="https://download.unsplash.com/44/fN6hZMWqRHuFET5YoApH_StBalmainCoffee.jpg">
                <div class="container">
                <div class="carousel-caption">
<h1>Welcome to my App!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-success btn-lg btn-custom" %>
    <%= link_to "View Products", products_path , class: "btn btn-primary btn-lg btn-custom2" %>
    <%= link_to "New Order", new_order_path, class: "btn btn-danger btn-lg btn-custom"%>
    <%= link_to "View Orders", orders_path, class: "btn btn-danger btn-lg btn-custom2"%>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg btn-custom" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg btn-custom2" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
            <div class="item">
            <img class="second-slide" src="https://download.unsplash.com/photo-1422207134147-65fb81f59e38">
                <div class="container">
                <div class="carousel-caption">
<h1>Welcome to my App!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-success btn-lg btn-custom" %>
    <%= link_to "View Products", products_path , class: "btn btn-primary btn-lg btn-custom2" %>
    <%= link_to "New Order", new_order_path, class: "btn btn-danger btn-lg btn-custom"%>
    <%= link_to "View Orders", orders_path, class: "btn btn-danger btn-lg btn-custom2"%>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg btn-custom" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg btn-custom2" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
                        <div class="item">
            <img class="third-slide" src="https://download.unsplash.com/photo-1422310299561-e3b8b45d859f">
                <div class="container">
                <div class="carousel-caption">
<h1>Welcome to my App!</h1>
    <p>
    <% if user_signed_in? %>
    <%= link_to "New Product", new_product_path , class: "btn btn-success btn-lg btn-custom" %>
    <%= link_to "View Products", products_path , class: "btn btn-primary btn-lg btn-custom2" %>
    <%= link_to "New Order", new_order_path, class: "btn btn-danger btn-lg btn-custom"%>
    <%= link_to "View Orders", orders_path, class: "btn btn-danger btn-lg btn-custom2"%>
    <% else %>      
    </p>

<p>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg btn-custom" %>
<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg btn-custom2" %>
</p>
    <% end %>
                </div>
                </div>
            </div>
        </div><!-- Left and right controls -->

        <a class="left carousel-control" data-slide="prev" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span></a> <a class=
        "right carousel-control" data-slide="next" href=
        "#carousel-example-generic"><span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span></a>
    </div>

app/views/shared/_stripe_checkout_button.html.erb
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key]%>"
    data-amount="2000"
    data-name="Demo Site"
    data-description="2 widgets ($20.00)"
    data-image="/assets/swiftax1.png">
  </script>